name: Deploy image to server

on:
  workflow_call:
    inputs:
      images:
        required: true
        type: string
      ssh-host:
        required: true
        type: string
      ssh-port:
        required: true
        type: string
      ssh-user:
        required: true
        type: string
      service-name:
        required: true
        type: string
    secrets:
      PUBLISH_SSH_PRIVATE_KEY:
        required: true
        description: Private SSH key with access to SSH server
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo '${{ inputs.images }}'
      - uses: actions/checkout@v4
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ inputs.ssh-host }}
          username: ${{ inputs.ssh-user }}
          port: ${{ inputs.ssh-port }}
          key: ${{ secrets.PUBLISH_SSH_PRIVATE_KEY }}
          script: |
            compose_file=~/_docker/docker-compose.yaml
            IFS=$'\n' images=(${{ inputs.images }})
            docker pull "${images[0]}"
            yqTemplate=".services.${{ inputs.service-name }}.image = \"${images[0]}\""
            yq e "$yqTemplate" -i ${compose_file}
            docker compose -f ${compose_file} up ${{ inputs.service-name }} -d --force-recreate
